### ISSUE TITLE
can't set SASL_JAAS_CONFIG

### ISSUE THREAD

**Issue by jcarpentier78** [GuillaumeWaignier/kafka_consumer_group_exporter#2]
I think, there's a problem when I set security parameter with space character in value. 
Example : docker run -e KAFKAEXPORTER_BOOTSTRAP_SERVERS=10.157.0.125:9092 -e KAFKAEXPORTER_SECURITY_PROTOCOL=SASL_PLAINTEXT -e KAFKAEXPORTER_SASL_MECHANISM=SCRAM-SHA-512 -e KAFKAEXPORTER_SASL_JAAS_CONFIG="org.apache.kafka.common.security.scram.ScramLoginModule required username=foo password=fooPassword;" -p 8080:8080 ianitrix/kafka-consumer-group-exporter:0.0.1-jre8 /bin/bash

try to replace /src/assembly/bin/consumer-offset-exporter.sh :

```sh
if [ "${use_env}" ]
then
  echo "#Generated config file" > ${config_file}
  for param in `env`
  do
    case ${param} in
      ${variable_prefix}* )
        key=`echo ${param} | sed -e "s/${variable_prefix}\(.*\)=.*/\1/g" | tr '[:upper:]' '[:lower:]' | sed -e 's/_/./g' `
        value=`echo ${param} | sed -e 's/.*=\(.*\)/\1/g' `
        echo ${key}=${value} >> ${config_file}
      ;;
    esac
  done
fi
```

by:

```sh
if [ "${use_env}" ]
then
  echo "#Generated config file" > ${config_file}
  IFS=$'\n'; 
  for param in `env`
  do
    case ${param} in
      ${variable_prefix}* )
        key=`echo ${param} | sed -e "s/${variable_prefix}\(.*\)=.*/\1/g" | tr '[:upper:]' '[:lower:]' | sed -e 's/_/./g' `
        value=`echo ${param} | sed -e 's/^[^=]*=\([. ]*\)/\1/g' `
        echo ${key}=${value} >> ${config_file}
      ;;
    esac
  done
fi
```

**Comment by GuillaumeWaignier** [comment]
The key format is more strict: only upper case, digit and _ are allowed.
